Main/urls.py
from django.urls import path, re_path
from . import views
from Main.views import *

app_name = 'main'
urlpatterns = [
    path('Stock/', views.stockMain, name="stock"),
    path('Stock/Inquiry/', views.readItems, name="readItems"),
    path('Stock/Add/Items/', views.addItems, name="addItems"),
    path('Stock/<int:pk>/Delete/', StockDelete.as_view(), name='deleteItem'),
    path('Stock/<int:pk>/Edit/', StockUpdate.as_view(), name='updateItem'),
    path('Stock/<pk>/Update/', views.ajaxStockUpdate, name="ajaxStockUpdate"),
    path('Order/Inquiry/', views.readOrders, name='readOrders'),
    path('Order/Add/Items/', views.addOrders, name='addOrders'),
    path('Order/<int:pk>/Delete/', OrderDelete.as_view(), name='deleteOrders'),
    path('Order/<int:pk>/Edit/', OrderUpdate.as_view(), name="updateOrder"),
    path('Order/<pk>/Incoming/', views.ajaxIncomingOrder, name="incomingOrder"),
    path('Stock/History/<page>', views.getStockHistory, name="getStockHistory"),

    path('Sell/', views.sell, name="sell"),
    path('Sell/Admin/', views.sellAdmin, name="sellAdmin"),
    path('Sell/Menu/Register/', views.sell_registerMenu, name="sell_registerMenu"),
    path('Sell/<int:pk>/Delete/', SellDelete.as_view(), name="sell_delete"),
    path('Sell/<int:pk>/Update/', SellUpdate.as_view(), name="sell_update"),

    path('Order/State/', views.orderState, name='orderState'),
    path('Order/past/', PastOrder.as_view(), name='pastOrder'),
    path('ajax/Order/<pk>/Done/', orderDone.as_view(), name='orderDone'),
    path('ajax/Order/<pk>/Cancel/', orderCancel.as_view(), name='orderCancel'),

    # 매출 관리
    path('Profit/', ProfitMain.as_view(), name="profit-main"),
    path('Profit/Search/', ProfitSearch.as_view(), name="profit-search"),
    path('Spending/', SpendingMain.as_view(), name="spending-main"),
    path('Spending/Search/', SpendingSearch.as_view(), name="spending-search"),

    # Api
    path('Menu/list/', MenuApi.as_view(), name='menu-list')
]

RMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls', namespace='main')),
    path('Ordering/', include('Order.urls')),
    path('Counter/', include('Counter.urls', namespace='counter'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/views.py
from django.shortcuts import render, HttpResponse, Http404, render_to_response, redirect
from .models import *
from django.forms.models import modelform_factory
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic import ListView
from django.views import View
import json
from django.core import serializers
from django.db.models import F, Sum, Count

# -------------- 재고 부분 ------------------#
# Main
def stockMain(request):
    return render(request, 'Main/Stock/main.html')

# 재고 조회
def readItems(request):
    try:
        Stocks = Stock.objects.all()
    except Exception as e:
        Stocks = None

    return render(request, 'Main/Stock/Stock_read_items.html', {
        'Stocks' : Stocks
    })

# 재고 등록
def addItems(request):
    if request.method == 'POST':
        s_name = request.POST.get('name')
        s_count = request.POST.get('number')
        s_unit = request.POST.get('unit')
        s_incoming_at = request.POST.get('date')
        s_caution_num = request.POST.get('alter_number')
        s_expire_at = request.POST.get('expire_date')

        Stock.objects.create(
            s_name = s_name,
            s_count = int(s_count),
            s_unit = s_unit,
            s_incoming_at = s_incoming_at,
            s_caution_num = s_caution_num,
            s_expire_at = s_expire_at
        )
        print("재고 생성 완료")
        return redirect('/Stock/Inquiry/', {
            'Stocks' : Stock.objects.all(),
        })

    return render(request, 'Main/Stock/Stock_add_item.html')

# 재고 수정
class StockUpdate(UpdateView):
    model = Stock
    fields = ['s_name', 's_count', 's_unit', 's_incoming_at', 's_caution_num',
                's_expire_at']
    success_url = '/Stock/Inquiry/'
    template_name = 'Main/Stock/Stock_update_item.html'
    
    def get_initial(self):
        initial = super(StockUpdate, self).get_initial()
        return initial

# 재고 소비 및 충당
def ajaxStockUpdate(request, pk):
    message = ""
    m_count = request.POST.get("change_value")
    type_ = request.POST.get("type")
    data = dict()
    try:
        stock = Stock.objects.get(id=pk)
        if type_ == '0':
            stock.s_count =stock.s_count+float(m_count)
        else:
            stock.s_count =stock.s_count-float(m_count)

        if not stock.stock_checking():
            stock.s_status = False
        else:
            stock.s_status = True

        stock.save(update_fields=['s_count', 's_status'])
        message = "성공적으로 변경되었습니다."
        data['count'] = str(stock.s_count) + stock.s_unit
    except Exception as e:
        message = "처리 도중 오류가 생겼습니다."

    data['message'] = message
    return HttpResponse(json.dumps(data), content_type='application/json')

# 재고 삭제
class StockDelete(DeleteView):
    model = Stock
    success_url = '/Stock/Inquiry/'
    template_name = 'Main/Stock/Stock_read_items.html'

# 이력 조회
def getStockHistory(request, page):
    print('request가 들어오냐?')
    bar_size = 5
    offset = 10
    page = int(page)
    datas = Stocklog.objects.all().order_by('-sl_created_at')
    return render(request, 'Main/Stock/stock_read_history.html', {
        'historys' : datas[(int(page)-1)*offset:int(page)*offset],
        'page' : page,
        'page_start_point' : (page-1)//bar_size*bar_size,
        'MAX_SIZE' : len(datas)//offset,
        'PAGE_SIZE' : bar_size
    })

# -------------- 발주 부분 ------------------#
# 발주 등록
def addOrders(request):
    if request.method == 'POST':
        o_name = request.POST.get('name')
        o_number = request.POST.get('number')
        o_date = request.POST.get('date')
        o_unit = request.POST.get('unit')
        o_target = request.POST.get('target')
        o_note = request.POST.get('note')
        
        Order.objects.create(
            o_name = o_name,
            o_count = int(o_number),
            o_order_at = o_date,
            o_unit = o_unit,
            o_target = o_target,
            o_note = o_note,
        )

        return redirect('/Order/Inquiry/', {
            'Orders' : Order.objects.all()
        })
    return render(request, 'Main/Order/Order_add_item.html')

# 발주 조회
def readOrders(request):
    try:
        Orders = Order.objects.all()
    except Exception as e:
        Orders = None

    return render(request, 'Main/Order/Order_read_items.html',{
        'Orders' : Orders,
    })

class OrderUpdate(UpdateView):
    model = Order
    success_url = "/Order/Inquiry/"
    template_name = "Main/Order/Order_update_item.html"
    fields = '__all__'

    def get_initial(self):
        return super().get_initial()

# 발주 반입처리
def ajaxIncomingOrder(request, pk):
    if request.method == 'POST':
        order = Order.objects.get(pk=pk)
        order.o_status = True
        order.save()

        # 반입 처리가 된다면 재고에 추가
        Stock.objects.create(
            s_name=order.o_name,
            s_count=order.o_count,
            s_unit=order.o_unit,
        )
        
        datas = {
            'message' : '성공적으로 처리 되었습니다.',
        }
        return HttpResponse(json.dumps(datas), content_type="application/json")

    return HttpResponse("실패")

# 발주 삭제
class OrderDelete(DeleteView):
    model = Order
    success_url = "/Order/Inquiry/"
    template_name = "Main/Order/Order_read_items.html"

##### 판매 관리 #####
def sell(request):
    return render(request, 'Main/Sell/main.html', {})

def sellAdmin(request):
    return render(request, 'Main/Sell/sell_menu_admin.html', {'menus' : Menu.objects.all() })

def sell_registerMenu(request):
    if request.method == 'POST':
        print(request.POST.keys(), request.POST.values())
        m_name = request.POST.get('name')
        m_price = request.POST.get('price')
        m_explain = request.POST.get('explain')
        m_pic = request.FILES.get('image')

        Menu.objects.create(m_name=m_name, m_price=m_price, m_explain=m_explain, m_pic=m_pic)
        return redirect('/Sell/Admin/')
    return render(request, 'Main/Sell/sell_menu_register.html')

class SellDelete(DeleteView):
    model = Menu
    success_url = "/Sell/Admin/"

class SellUpdate(UpdateView):
    model = Menu
    success_url = "/Sell/Admin/"
    template_name = "Main/Sell/sell_menu_update.html"
    fields = "__all__"

    def get_initial(self):
        initial = super(UpdateView, self).get_initial()
        return initial


##### 주문 현황 ### 향후 이식
def orderState(request):
    order = Table_order.objects.filter(to_isActive=True).order_by('-to_order_sheet__os_order_date')
    return render(request, 'Main/Order_State/index.html', {'orders' : order})

# 지난 주문
class PastOrder(ListView):
    model = Table_order
    template_name = 'Main/Order_State/Order_past.html'
    context_object_name = 'datas'

    def get_queryset(self):
        return Table_order.objects.filter(to_isActive=False).order_by('-to_order_sheet__os_order_date')
        

# 주문 완료 처리
class orderDone(View):
    def post(self, request, *args, **kwargs):
        order_pk = kwargs.get('pk')
        obj = Table_order.objects.get(pk=order_pk)
        obj.to_status = '완료'
        obj.save(update_fields=['to_status', ])
        return HttpResponse(json.dumps({'status' : '완료', }), content_type="json/application")

# 주문 취소 처리
class orderCancel(View):
    def post(self, request, **kwargs):
        order_pk = kwargs.get('pk')
        obj = Table_order.objects.get(pk=order_pk)
        obj.to_status = '취소'
        obj.to_isActive = False
        obj.save(update_fields=['to_status', 'to_isActive'])
        return HttpResponse(json.dumps({'status' : '취소', }), content_type="json/application")



#### 매출 관리 ####

# 수익 관리
class ProfitMain(View):
    def get(self, request, *args, **kwargs):
        profits = Profit.objects.all().order_by('-p_profit_date')
        amount = profits.aggregate(amount=Sum('p_amount'))
        return render(request, 'Main/Profit/main.html', {'profits' : profits, 'amount' : amount['amount']})

class ProfitSearch(View):
    def post(self, request, *args, **kwargs):
        datas = {}
        start_date = request.POST.get('start-date')
        end_date = request.POST.get('end-date')
        if end_date == "" and start_date == "":
            pass
        elif end_date == "":
            datas = Profit.objects.filter(p_profit_date__year=start_date[:4], \
                p_profit_date__month=start_date[5:7], p_profit_date__day=start_date[8:10] ).order_by('-p_profit_date')
        else:
            datas = Profit.objects.filter(p_profit_date__gte=start_date, p_profit_date__lte=end_date).order_by('-p_profit_date')
        amount = datas.aggregate(amount=Sum('p_amount'))
        return render(request, 'Main/Profit/main.html', {'profits' : datas, 'amount' : amount['amount']})

# 지출 관리
class SpendingMain(View):
    def get(self, request, *args, **kwargs):
        datas = Spending.objects.all().order_by('-s_spending_date')
        return render(request, 'Main/Profit/Spending_main.html', {'spending' : datas})

class SpendingSearch(View):
    def post(self, request, *args, **kwargs):
        datas = {}
        start_date = request.POST.get('start-date')
        end_date = request.POST.get('end-date')
        if end_date == "" and start_date == "":
            pass
        elif end_date == "":
            datas = Spending.objects.filter(s_spending_date__year=start_date[:4], \
                s_spending_date__month=start_date[5:7], s_spending_date__day=start_date[8:10] ).order_by('-s_sending_date')
        else:
            datas = Spending.objects.filter(s_spending_date__gte=start_date, s_spending_date__lte=end_date).order_by('-s_sending_date')
        return render(request, 'Main/Profit/Spending_main.html', {'spending' : datas, })

### REST API ####
class MenuApi(View):
    def get(self, request, *args, **kwargs):
        datas = Menu.objects.all()
        print(datas)
        datas_to_JSON = serializers.serialize('json', datas)
        print(datas_to_JSON)
        return HttpResponse(datas_to_JSON, content_type="json/application")

Main/templates/Main/Stock/Stock_add_item.html
{% extends 'Main/Stock/main.html' %}

{% block content %}
    <form action="{% url 'main:addItems' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>재고명</label>
                <input type="text" name="name" class="form-control" placeholder="재고 관리를 원하는 재고 이름">
            </div>
            <div class='form-group col-md-5'>
                <label>잔량</label>
                <input type="number" name="number" class="form-control" placeholder="남아 있는 재고의 수량을 입력해 주세요..">
            </div>
            <div class="form-group col-md-1">
                <label>단위</label>
                <input type="text" name="unit" class="form-control" placeholder="단위">
            </div>
        </div>
        <div class="form-group">
            <label>경고 수량</label>
            <input type="number" name="alter_number" class="form-control" placeholder="경고 수량은 입력한 값 이하로 재고량이 떨어지면 알람을 해 주는 기능입니다.">
        </div>
        <div class="form-group">
            <label>반입일자</label>
            <input class="form-control" type="date" name="date" placeholder="반입날짜">
        </div>
        <div class="form-group">
            <label>유통기한</label>
            <input class="form-control" type="date" name="expire_date" placeholder="유통기한">
        </div>

        <input class="btn btn-info" type="submit" value="등록">
    </form>
{% endblock %}

Main/templates/Main/Stock/Stock_read_items.html
{% extends 'Main/Stock/main.html' %}

{% block content %}
    <table class="table table-bordered text-center">
    <thead class="thead thead-light">
        <th>품명</th>
        <th>재고량</th>
        <th>반입일자</th>
        <th>유통기한</th>
        <th>상태</th>
        <th style="width : 10%;">수량 조절<i id="tooltip" class="glyphicon glyphicon-info-sign" style="color : blue" title="기존 재고량에 재고를 쉽게 더하거나 뺄 수 있습니다."></i></th>
        <th>삭제 및 수정</th>
    </thead>
    <tbody>
    {% if Stocks %}
        {% for stock in Stocks %}
        <tr>
            <td>{{stock.s_name}}</td>
            <td id="count{{stock.pk}}">{{stock.s_count}}{{stock.s_unit}}</td>
            <td>{{stock.s_incoming_at|default_if_none:"설정이 필요합니다."}}</td>
            <td>{{stock.s_expire_at|default_if_none:"설정이 필요합니다."}}</td>
            {% if stock.s_status == True %}
                <td>재고 있음</td>
            {% else %}
                <td>소진</td>
            {% endif %}
            <td>
                <input id="value{{stock.pk}}" type="number" class="form-control" placeholder="변경 값">
                <i class="glyphicon glyphicon-plus-sign" style="font-size : 20px;" onclick="modifyValue(0, {{stock.s_count}}, {{stock.pk}})"></i>
                <i class="glyphicon glyphicon-minus-sign" style="font-size : 20px;" onclick="modifyValue(1, {{stock.s_count}}, {{stock.pk}})"></i>
            </td>
            <td>
                <form name="update" method="GET" action="{% url 'main:updateItem' stock.pk %}" style="display : inline;">
                    <input type="submit" class="btn btn-info" value="수정">
                </form>
                <form name="delete" method="POST" style="display : inline;">
                    {% csrf_token %}
                    <input type="button" class="btn btn-danger" value="삭제" onclick="isDelete({{stock.pk}});">
                </form>
            </td>
        </tr>
        {% endfor %}
    {% else %}
        <td colspan="8">등록된 재고가 없습니다.</td>
    {% endif %}
    </tbody>
    </table>
    

    <script>
    function isDelete(num){
    if(confirm("정말 삭제하시겠습니까?"))
        {
            var url = "/Stock/"+num+"/Delete/"
            $("form[name='delete']").attr("action", url);
            $("form[name='delete']").submit();
        }
    }

    $(document).ready(function(){
        $("#tooltip").tooltip();
    });

        // 수량 조절
        // type = 0 -> 추가
        // type = 1 -> 삭제
        function modifyValue(type, pre_val, pk){
            var val = Number($("#value" + pk).val());
            var request_url = "/Stock/"+pk+"/Update/";
            if (val > pre_val && type == 1){
                alert("기존 재고량보다 큰 값을 소비할 수 없습니다.");
                return 0;
            }else if (val == ""){
                alert("값을 입력해 주세요.");
                return 0;
            }

            if (type==0){
                 $.ajax({
                    type : 'POST',
                    url : request_url,
                    data : {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'change_value' : val,
                        'type' : '0'
                    },
                    success : function(res){
                        alert(res.message);
                        $("td#count" + pk).html(res.count + "");
                        location.reload();
                    }
                 });
            }else if(type==1){
                 $.ajax({
                    type : 'POST',
                    url : request_url,
                    data : {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'change_value' : val,
                        'type' : '1'
                    },
                    success : function(res){
                        alert(res.message);
                        $("td#count" + pk).html(res.count + "");
                        location.reload();
                    }
                 });
            }
        }
    </script>
{% endblock %}

Main/templates/Main/Stock/Stock_sidebar.html
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="glyphicon glyphicon-shopping-cart"></i>재고·유통</h3>
    </div>

    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'main:readItems' %}">재고 조회</a></li>
        <li class="list-group-item"><a href="{% url 'main:addItems' %}">재고 등록</a></li>
        <li class="list-group-item"><a href="{% url 'main:readOrders' %}">발주 조회</a></li>
        <li class="list-group-item"><a href="{% url 'main:addOrders' %}">발주 등록</a></li>
        <li class="list-group-item"><a href="{% url 'main:getStockHistory' 1 %}">이력 확인</a></li>
    </ul>
</div>

Main/templates/Main/Stock/Stock_update_item.html
{% extends 'Main/Stock/main.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-info" type="submit" value="수정">
</form>
{% endblock %}

Main/templates/Main/Stock/main.html
{% extends 'Main/Based/main.html' %}
{% load static %}
{% block title %}유통·재고{% endblock %}
{% block sidebar %}
   {% include 'Main/Stock/Stock_sidebar.html' %}
{% endblock %}

{% block script %}
    <script src="{% static 'Main/js/Stock.js' %}"></script>
{% endblock%}

{% block content %}
    안주영에 의한.
{% endblock %}

Main/templates/Main/Stock/stock_read_history.html
{% extends 'Main/Stock/main.html' %}

{% block content %}

<div class="row">
<table class="table table-hover table-bordered">
<thead class="thead thead-light">
    <th>시간</th>
    <th>이력 내용</th>
</thead>
<tbody>
{% for history in historys %}
    <tr>
        <td>{{history.sl_created_at}}</td>
        <td>{{history.sl_log}}</td>
    </tr>
{% endfor %}
</tbody>
</table>
</div>
<div class="row">
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" onclick="Previous();">이전</a></li>
        <li id='p1' class="page-item"><a id='p1' class="page-link" onclick="gotopage(this.id)"></a></li>
        <li id='p2' class="page-item"><a id='p2' class="page-link" onclick="gotopage(this.id)"></a></li>
        <li id='p3' class="page-item"><a id='p3' class="page-link" onclick="gotopage(this.id)"></a></li>
        <li id='p4' class="page-item"><a id='p4' class="page-link" onclick="gotopage(this.id)"></a></li>
        <li id='p5' class="page-item"><a id='p5' class="page-link" onclick="gotopage(this.id)"></a></li>
        <li class="page-item"><a class="page-link" onclick="Next();">다음</a></li>
    </ul>
</div>

<script>
    var page = Number('{{page}}');
    var page_start_point = Number('{{page_start_point}}');
    var MAX_SIZE = Number("{{MAX_SIZE}}");
    var PAGE_SIZE = Number("{{PAGE_SIZE}}");

    

    $(document).ready(function(){
        var index = 1;
        for(var i=Number(page_start_point); i<Number(page_start_point)+5; i++)
        {   
            $("a#p" + index).html(i+1);
            $("li#p" + index++).attr("v", i);
        }
        $("li[v="+(page-1)+"]").addClass("active");
        
    })

    function gotopage(id)
    {
        var clicked_page = $("a#" + id).html();
        console.log(clicked_page);
        var url = '/Stock/History/' + clicked_page;
        window.location.href = url;
    }

    function Previous()
    {
        if(page_start_point-5<0){
            return false;
        }   
        var url = '/Stock/History/' + page_start_point;
        window.location.href = url;
    }
    
    function Next()
    {
        if (page_start_point+PAGE_SIZE > MAX_SIZE){
            return false;
        }
        var next_Index = page_start_point+PAGE_SIZE+1;
        var url = '/Stock/History/' + next_Index;
        window.location.href = url;
    }
</script>
{% endblock %}